// src/output/header.rs

use crate::constants;
use anyhow::Result;
use std::io::Write;

/// Writes the global file header (e.g., "# File generated by DirCat") to the output.
pub fn write_global_header(writer: &mut dyn Write) -> Result<()> {
    write!(writer, "{}", constants::OUTPUT_FILE_HEADER)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants;

    #[test]
    fn test_write_header() -> Result<()> {
        let mut output = Vec::new();
        write_global_header(&mut output)?;
        let output_str = String::from_utf8(output)?;
        assert_eq!(output_str, constants::OUTPUT_FILE_HEADER);
        Ok(())
    }
}
